### PR TITLE
Add safe mode

### PR DESCRIPTION
**Pull request by ekr**

### CODE REVIEW

**Comment by ekr** [comment]
@bifurcation WHY HAVE YOU NOT LANDED THIS PATCH? I have been a bad-attitude user since 2005 and I can't believe you have betrayed the users like this.

**Comment by martinthomson** [comment]
WONTFIX

**Comment by martinthomson** [comment]
We will only accept this if you also add a `/godmode` command.

**Comment by ekr** [comment]
@martinthomson what should /godmode do?

**Comment by martinthomson** [comment]
Anything like this needs a remote override.

**Comment by ekr** [comment]
What about on override for the remote override?

**Pull request closed without merging**
